import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Router, { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { createGroup, fetchGroup, manageGroupMembers, updateGroup } from '../api/user'
import { useUser } from '../contexts/userContext'
import styles from '../styles/Home.module.css'
import Cookies from 'js-cookie'
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import PositionedMenu from '../components/PositionedMenu'
import MenuItem from '@mui/material/MenuItem';
import CollapsibleTable from '../components/CollapsibleTable'
import TableGroupRow from '../components/TableGroupRow'
import Box from '@mui/material/Box';
import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';
import EditIcon from '@mui/icons-material/Edit';
import FavoriteIcon from '@mui/icons-material/Favorite';
import NavigationIcon from '@mui/icons-material/Navigation';
import EditGroupDialog from '../components/EditGroupDialog'
import { group } from 'console'
export interface Groups {
  groups: Group[];
}

export interface Group {
  id: string;
  name: string;
  description: string;
  type: boolean;
  roles: Item[];
  people: Item[];
  members: number;
}

export interface Item {
  id: string;
  name: string;
  active: boolean;
}



const Home: NextPage = () => {
  const accessToken = () => Cookies.get('access_token')
  const [groups, setGroups] = useState<Group[]>()


  const router = useRouter()
  const fetchGroups = async () => {
    try {
      const response = await fetchGroup(accessToken())
      const result: Groups = await response.json()
      if (response.status > 200) throw Error("response")
      setGroups(result.groups)
    } catch (e) {
      console.log(e)
    }
  }

  useEffect(() => {
    if (!accessToken()) {
      router.replace("/login");
    } else {
      fetchGroups()
    }
  }, [])

  const [openDialog, setOpenDialog] = useState(false);

  const handleClickOpenDialog = () => {
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
  };

  const handleSubmitData = async (newData: Group) => {
    const accessToken = () => Cookies.get('access_token');
    const response = await createGroup(accessToken(), { name: newData.name, description: newData.description })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Group Table React Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Group Table React Demo</h1>
        <TableContainer component={Paper} >
          <Table sx={{ minWidth: 650 }} aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>
                  Name
                </TableCell>
                <TableCell>
                  Description
                </TableCell>

                <TableCell>
                  People
                </TableCell>
                <TableCell>
                  Roles
                </TableCell>
                <TableCell>

                </TableCell>

              </TableRow>
            </TableHead>
            <TableBody>
              {groups?.map(group => {
                return (
                  <TableGroupRow key={group.id} data={group} />)
              }
              )}
            </TableBody>
          </Table>
        </TableContainer>

        <Fab color="primary" aria-label="add" sx={{
          position: 'fixed',
          bottom: 16,
          right: 16,
        }} onClick={() => { setOpenDialog(true) }}>
          <AddIcon />
        </Fab>
        <EditGroupDialog data={{}} onClose={handleCloseDialog} openDialog={openDialog}

          handleSubmitData={(newData: Group) => handleSubmitData(newData)}
        />
      </main>


    </div >
  )
}

export default Home

