import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent, useState } from 'react'
import Button from '../components/button'
import Input from '../components/input'
import styles from '../styles/Login.module.css'

const Home: NextPage = () => {

  const [username, setUsername] = useState("")
  const [password, setPassword] = useState("")




  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.page}>

        <div className={styles.login}>
          <Image src="/logo_original 1.png" width={220} height={72} />

          <Input title='Email' placeholder='Email' value={username} onChange={(e) => { setUsername(e.target.value) }} />

          <Input title='Password' placeholder='Password' value={password} onChange={(e) => { setPassword(e.target.value) }} />

          <Button onClick={() => { console.log("button click") }}>Sign Up</Button>
        </div>
        <div className={styles.background}>        <Image src="/background.png" layout="fill" objectFit='cover' />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
